##
# Copyright (c) Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

# Routing file

all:
  # -- HOME ROUTING --
  home:
    route: /
    controller: \Eureka\Package\Core\Controller\Home::index

  page:
    route: /page/:page_name
    controller: \Eureka\Package\Core\Controller\Page::dynamic
    required:
      page_name: string
