##
# Copyright (c) Romain Cottard
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
##

# File to configure twig layout / templates


all:
  home:
    template: '__DIR__/../resources/template'

